---
- name: use vhost role playbook
  hosts: all
  user: ansible
  become: true 

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - myvhost:
    
  post_tasks:
    - debug:
        msg: 'Web server has been configurated.'a